
const allAgentsData = [
  {
    id: "AG001",
    rowId: "AG001",
    fullName: "John Smith",
    dateOfBirth: "1990-03-15",
    townOfBirth: "London",
    nationality: "British",
    hometown: "Manchester",
    contact: "+233 24 123 4567",
    email: "john.smith@example.com",
    gpsAddress: "123 Main St, London",
    agentCas: "John Smith",
    agentPicture: "https://www.seekpng.com/png/detail/110-1100707_silhouette-person-png.png",
    guarantor1FullName: "Jane Doe",
    guarantor1Contact: "jane.doe@example.com",
    guarantor1GhanaCard: "GHA123456789",
    guarantor2FullName: "Bob Wilson",
    guarantor2Contact: "bob.wilson@example.com",
    guarantor2GhanaCard: "GHA987654321",
    affiliateAssoc: "London Transport",
    japtuIdCardNumber: "JT123456",
    status: "Active"
  },
  {
    id: "AG002",
    rowId: "AG002",
    fullName: "Sarah Johnson",
    dateOfBirth: "1988-07-22",
    townOfBirth: "Birmingham",
    nationality: "British",
    hometown: "Leeds",
    contact: "+233 20 987 6543",
    email: "sarah.j@example.com",
    gpsAddress: "456 High St, Birmingham",
    agentCas: "Sarah Johnson",
    agentPicture: "https://www.seekpng.com/png/detail/110-1100707_silhouette-person-png.png",
    guarantor1FullName: "Mike Thompson",
    guarantor1Contact: "mike.t@example.com",
    guarantor1GhanaCard: "GHA234567890",
    guarantor2FullName: "Alice Brown",
    guarantor2Contact: "alice.b@example.com",
    guarantor2GhanaCard: "GHA345678901",
    affiliateAssoc: "Birmingham Transport",
    japtuIdCardNumber: "JT234567",
    status: "Active"
  },
  {
    id: "AG003",
    rowId: "AG003",
    fullName: "Michael Brown",
    dateOfBirth: "1992-11-30",
    townOfBirth: "Liverpool",
    nationality: "British",
    hometown: "Manchester",
    contact: "+233 27 456 7890",
    email: "m.brown@example.com",
    gpsAddress: "789 Church St, Liverpool",
    agentCas: "Michael Brown",
    agentPicture: "https://www.seekpng.com/png/detail/110-1100707_silhouette-person-png.png",
    guarantor1FullName: "David Clark",
    guarantor1Contact: "david.c@example.com",
    guarantor1GhanaCard: "GHA456789012",
    guarantor2FullName: "Emma White",
    guarantor2Contact: "emma.w@example.com",
    guarantor2GhanaCard: "GHA567890123",
    affiliateAssoc: "Liverpool Transport",
    japtuIdCardNumber: "JT345678",
    status: "Suspended"
  },
  {
    id: "AG004",
    rowId: "AG004",
    fullName: "Emma Wilson",
    dateOfBirth: "1995-04-18",
    townOfBirth: "Glasgow",
    nationality: "British",
    hometown: "Edinburgh",
    contact: "+233 23 789 0123",
    email: "emma.w@example.com",
    gpsAddress: "321 Queen St, Glasgow",
    agentCas: "Emma Wilson",
    agentPicture: "https://www.seekpng.com/png/detail/110-1100707_silhouette-person-png.png",
    guarantor1FullName: "James Miller",
    guarantor1Contact: "james.m@example.com",
    guarantor1GhanaCard: "GHA678901234",
    guarantor2FullName: "Sophie Taylor",
    guarantor2Contact: "sophie.t@example.com",
    guarantor2GhanaCard: "GHA789012345",
    affiliateAssoc: "Glasgow Transport",
    japtuIdCardNumber: "JT456789",
    status: "Active"
  },
  {
    id: "AG005",
    rowId: "AG005",
    fullName: "David Lee",
    dateOfBirth: "1991-09-25",
    townOfBirth: "Cardiff",
    nationality: "British",
    hometown: "Swansea",
    contact: "+233 26 234 5678",
    email: "david.lee@example.com",
    gpsAddress: "654 Park Rd, Cardiff",
    agentCas: "David Lee",
    agentPicture: "https://www.seekpng.com/png/detail/110-1100707_silhouette-person-png.png",
    guarantor1FullName: "Laura Jones",
    guarantor1Contact: "laura.j@example.com",
    guarantor1GhanaCard: "GHA890123456",
    guarantor2FullName: "Peter Wright",
    guarantor2Contact: "peter.w@example.com",
    guarantor2GhanaCard: "GHA901234567",
    affiliateAssoc: "Cardiff Transport",
    japtuIdCardNumber: "JT567890",
    status: "Inactive"
  }
];

export default allAgentsData;
