export const data = [
  {
    rowId: "ML001",
    pickupLocation: "Tema Port",
    deliveryLocation: "Kumasi Central",
    pickupDate: "2024-02-01",
    status: "Pending",
    weight: "4,500 kg",
    length: "20 ft",
    equipmentType: "Container",
    rate: 2800,
  },
  {
    rowId: "ML002",
    pickupLocation: "Accra Port",
    deliveryLocation: "Tamale Central",
    pickupDate: "2024-02-02",
    status: "Pending",
    weight: "3,200 kg",
    length: "18 ft",
    equipmentType: "Flatbed",
    rate: 3200,
  },
  {
    rowId: "ML003",
    pickupLocation: "Takoradi Port",
    deliveryLocation: "Ho Market",
    pickupDate: "2024-02-03",
    status: "Pending",
    weight: "5,100 kg",
    length: "22 ft",
    equipmentType: "Container",
    rate: 3500,
  },
  {
    rowId: "ML004",
    pickupLocation: "Tema Industrial",
    deliveryLocation: "Sunyani Central",
    pickupDate: "2024-02-04",
    status: "Pending",
    weight: "2,800 kg",
    length: "16 ft",
    equipmentType: "Van",
    rate: 2600,
  },
  {
    rowId: "ML005",
    pickupLocation: "Accra Airport",
    deliveryLocation: "Wa Central",
    pickupDate: "2024-02-05",
    status: "Pending",
    weight: "3,900 kg",
    length: "19 ft",
    equipmentType: "Flatbed",
    rate: 3800,
  },
  {
    rowId: "ML002",
    pickupLocation: "Accra Airport",
    deliveryLocation: "Takoradi",
    pickupDate: "2024-02-03",
    status: "In Progress",
    weight: "2,200 kg",
    length: "15 ft",
    equipmentType: "Flatbed",
    rate: 1900,
  },
  {
    rowId: "ML003",
    pickupLocation: "Spintex Road",
    deliveryLocation: "Cape Coast",
    pickupDate: "2024-02-05",
    status: "Completed",
    weight: "3,800 kg",
    length: "18 ft",
    equipmentType: "Flatbed",
    rate: 2200,
  },
];

export default data;
