const agentLoadboardData = [
    {
        id: "669875",
        rowId: "669875",
        pickupLocation: "Airport City, Accra",
        deliveryLocation: "Adum, Kumasi",
        pickupDate: "July 27, 2024",
        distance: "252 km",
        confirmedRate: 3200,
        marketRate: 3000,
        weight: "1,800 kg",
        length: "11.5 ft",
        age: "15 minutes",
        equipmentType: "V: Van",
        equipment: {
            type: "V: Van",
            length: "11.5 ft",
            weight: "1,800 kg",
            commodity: "Laptops & Electronics",
            load: "Full",
        },
        postedTime: "15 minutes ago",
        shipmentDetails: {
            pickUpDate: "07/28",
            pickUpHours: "9:00 AM - 4:00 PM",
            dockHours: "8:00 AM - 3:00 PM",
            reference: "GH8842235",
            comments:
                "Insurance included - Air-conditioned van required - No stacking",
        },
        rateDetails: {
            total: 3200,
            trip: "252 km",
            ratePerKm: 12.7,
        },
        companyDetails: {
            name: "CompuGhana Distribution",
            telephone: "0544-567-8901",
            mcNumber: "GHA1567443",
            location: "Airport City, Accra",
            creditScore: 95,
            daysToPay: "14 T/A",
            reviews: {
                score: 4.5,
                count: 43,
            },
        },
        status: "In Progress",
    },
    {
        id: "669876",
        rowId: "669876",
        pickupLocation: "Tema Port",
        deliveryLocation: "Takoradi Harbor",
        pickupDate: "July 28, 2024",
        distance: "218 km",
        confirmedRate: 2800,
        marketRate: 2600,
        weight: "2,500 kg",
        length: "20 ft",
        age: "30 minutes",
        equipmentType: "C: Container",
        equipment: {
            type: "C: Container",
            length: "20 ft",
            weight: "2,500 kg",
            commodity: "Industrial Equipment",
            load: "Full",
        },
        postedTime: "30 minutes ago",
        shipmentDetails: {
            pickUpDate: "07/28",
            pickUpHours: "7:00 AM - 2:00 PM",
            dockHours: "6:00 AM - 1:00 PM",
            reference: "GH8842236",
            comments: "Heavy machinery - Special handling required",
        },
        rateDetails: {
            total: 2800,
            trip: "218 km",
            ratePerKm: 12.8,
        },
        companyDetails: {
            name: "Tema Industrial Solutions",
            telephone: "0244-123-4567",
            mcNumber: "GHA1567444",
            location: "Tema Port",
            creditScore: 92,
            daysToPay: "30 T/A",
            reviews: {
                score: 4.2,
                count: 38,
            },
        },
        status: "In Progress",
    },
    {
        id: "669877",
        rowId: "669877",
        pickupLocation: "Achimota Mall, Accra",
        deliveryLocation: "Cape Coast",
        pickupDate: "July 29, 2024",
        distance: "144 km",
        confirmedRate: 1900,
        marketRate: 1800,
        weight: "1,200 kg",
        length: "15 ft",
        equipmentType: "R: Refrigerated",
        age: "1 hour",
        equipment: {
            type: "R: Refrigerated",
            length: "15 ft",
            weight: "1,200 kg",
            commodity: "Fresh Produce",
            load: "Full",
        },
        postedTime: "1 hour ago",
        shipmentDetails: {
            pickUpDate: "07/29",
            pickUpHours: "6:00 AM - 12:00 PM",
            dockHours: "5:00 AM - 11:00 AM",
            reference: "GH8842237",
            comments:
                "Temperature-controlled transport required - Perishable goods",
        },
        rateDetails: {
            total: 1900,
            trip: "144 km",
            ratePerKm: 13.2,
        },
        companyDetails: {
            name: "Fresh Foods GH",
            telephone: "0302-789-0123",
            mcNumber: "GHA1567445",
            location: "Achimota Mall, Accra",
            creditScore: 88,
            daysToPay: "7 T/A",
            reviews: {
                score: 4.0,
                count: 25,
            },
        },
        status: "Completed",
    },
];

export default agentLoadboardData;
