const pendingAgentsData = [
    {
        id: "4",
        rowId: "4",
        fullName: "Alice Smith",
        dateOfBirth: "1992-08-15",
        townOfBirth: "Los Angeles",
        nationality: "USA",
        hometown: "San Francisco",
        contact: "alice.smith@example.com",
        email: "alice.smith@example.com",
        gpsAddress: "789 Elm Street, San Francisco, CA 94107",
        agentCas: "Alice Smith",
        agentPicture: "https://www.seekpng.com/png/detail/110-1100707_silhouette-person-png.png",
        guarantor1FullName: "Bob Johnson",
        guarantor1Contact: "bob.johnson@example.com",
        guarantor1GhanaCard: "9876543210987654",
        guarantor2FullName: "Cathy Green",
        guarantor2Contact: "cathy.green@example.com",
        guarantor2GhanaCard: "1234567890123456",
        affiliateAssoc: "Alice Smith",
        japtuIdCardNumber: "5678901234567890",
        status: "In progress",
    },
    {
        rowId: "2",
        fullName: "Michael Brown",
        dateOfBirth: "1985-05-22",
        townOfBirth: "Chicago",
        nationality: "USA",
        hometown: "Houston",
        contact: "michael.brown@example.com",
        email: "michael.brown@example.com",
        gpsAddress: "456 Pine Street, Houston, TX 77002",
        agentCas: "Michael Brown",
        agentPicture: "https://www.seekpng.com/png/detail/110-1100707_silhouette-person-png.png",
        guarantor1FullName: "Lisa White",
        guarantor1Contact: "lisa.white@example.com",
        guarantor1GhanaCard: "8765432109876543",
        guarantor2FullName: "James Black",
        guarantor2Contact: "james.black@example.com",
        guarantor2GhanaCard: "2345678901234567",
        affiliateAssoc: "Michael Brown",
        japtuIdCardNumber: "6789012345678901",
        status: "Suspended",
    },
    {
        rowId: "6",
        fullName: "Sophie Taylor",
        dateOfBirth: "1995-12-03",
        townOfBirth: "Boston",
        nationality: "USA",
        hometown: "Seattle",
        contact: "sophie.taylor@example.com",
        email: "sophie.taylor@example.com",
        gpsAddress: "123 Oak Avenue, Seattle, WA 98101",
        agentCas: "Sophie Taylor",
        agentPicture: "https://www.seekpng.com/png/detail/110-1100707_silhouette-person-png.png",
        guarantor1FullName: "Tom Hardy",
        guarantor1Contact: "tom.hardy@example.com",
        guarantor1GhanaCard: "5432109876543210",
        guarantor2FullName: "Emily Davis",
        guarantor2Contact: "emily.davis@example.com",
        guarantor2GhanaCard: "3456789012345678",
        affiliateAssoc: "Sophie Taylor",
        japtuIdCardNumber: "7890123456789012",
        status: "Approved",
    },
    {
        rowId: "1",
        fullName: "Daniel Lee",
        dateOfBirth: "1990-07-11",
        townOfBirth: "Miami",
        nationality: "USA",
        hometown: "Atlanta",
        contact: "daniel.lee@example.com",
        email: "daniel.lee@example.com",
        gpsAddress: "345 Maple Drive, Atlanta, GA 30303",
        agentCas: "Daniel Lee",
        agentPicture: "https://www.seekpng.com/png/detail/110-1100707_silhouette-person-png.png",
        guarantor1FullName: "Sarah Connor",
        guarantor1Contact: "sarah.connor@example.com",
        guarantor1GhanaCard: "0123456789012345",
        guarantor2FullName: "Chris Evans",
        guarantor2Contact: "chris.evans@example.com",
        guarantor2GhanaCard: "4567890123456789",
        affiliateAssoc: "Daniel Lee",
        japtuIdCardNumber: "9012345678901234",
        status: "Approved",
    },
    {
        rowId: "5",
        fullName: "Emma Wilson",
        dateOfBirth: "1988-03-19",
        townOfBirth: "Dallas",
        nationality: "USA",
        hometown: "Denver",
        contact: "emma.wilson@example.com",
        email: "emma.wilson@example.com",
        gpsAddress: "678 Birch Road, Denver, CO 80202",
        agentCas: "Emma Wilson",
        agentPicture: "https://www.seekpng.com/png/detail/110-1100707_silhouette-person-png.png",
        guarantor1FullName: "Nathan Drake",
        guarantor1Contact: "nathan.drake@example.com",
        guarantor1GhanaCard: "0987654321098765",
        guarantor2FullName: "Mia Wong",
        guarantor2Contact: "mia.wong@example.com",
        guarantor2GhanaCard: "5678901234567890",
        affiliateAssoc: "Emma Wilson",
        japtuIdCardNumber: "0123456789012345",
        status: "In progress",
    },
    {
        rowId: "3",
        fullName: "David Johnson",
        dateOfBirth: "1993-10-29",
        townOfBirth: "San Diego",
        nationality: "USA",
        hometown: "Phoenix",
        contact: "david.johnson@example.com",
        email: "david.johnson@example.com",
        gpsAddress: "890 Cedar Lane, Phoenix, AZ 85001",
        agentCas: "David Johnson",
        agentPicture: "https://www.seekpng.com/png/detail/110-1100707_silhouette-person-png.png",
        guarantor1FullName: "Olivia Parker",
        guarantor1Contact: "olivia.parker@example.com",
        guarantor1GhanaCard: "6789012345678901",
        guarantor2FullName: "Ethan Hunt",
        guarantor2Contact: "ethan.hunt@example.com",
        guarantor2GhanaCard: "1234567890123456",
        affiliateAssoc: "David Johnson",
        japtuIdCardNumber: "3456789012345678",
        status: "Denied",
    },
];

export default pendingAgentsData;
